### ISSUE TITLE
Missing Mozilla option in Submit an apllication form

### ISSUE THREAD

**Issue by cassiass** [sarahsharp/outreachy-django-wagtail#1]
Hello, I'm unable to find the Mozilla option in the "Select organization" field.

![image](https://user-images.githubusercontent.com/4005687/30704745-ff898d38-9ec9-11e7-98df-6a46803e261f.png)

**Comment by sarahsharp** [comment]
Mozilla wasn't added yet, but it is now. Sorry for this issue getting lost!
